---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---



## Loading and preprocessing the data

# Set work directory 

 setwd("C:/Users/C011204/Documents/R/HW2RR")

 getwd()

# Read in data

 activity <- read.csv("activity.csv")

# Pull up plotting package

library(ggplot2)

# Create weeekday variable and format date time 

activity$day <- weekdays(as.Date(activity$date))
activity$DateTime<- as.POSIXct(activity$date, format="%Y-%m-%d")



## What is mean total number of steps taken per day?

## Calculate the total number of steps taken per day

## summarizing total steps per date

sumsteps <- aggregate(activity$steps ~ activity$date, FUN=sum, )

colnames(sumsteps)<- c("Date", "Steps")

## Creating the historgram of total steps per day

hist(sumsteps$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day")

## Calculate the Mean of total steps taken per day 

as.integer(mean(sumsteps$Steps))


## Calculate the Median of total steps taken per day 

as.integer(median(sumsteps$Steps))


## What is the average daily activity pattern?

## Create time series plot of average steps per interval 

## Creating dataset with missing values removed 

nomiss <- activity[!is.na(activity$steps),]

## Create average number of steps per interval

intervaldata <- ddply(nomiss, .(interval), summarize, Avg = mean(steps))

## Create line plot of average number of steps per interval

p <- ggplot(intervaldata, aes(x=interval, y=Avg), xlab = "Interval", ylab="Average Number of Steps")
p + geom_line()+xlab("Interval")+ylab("Average Number of Steps")+ggtitle("Average Number of Steps per Interval")

## Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

## Calculate maximum steps by interval

maximumSteps <- max(intervaldata$Avg)

## Which interval contains the maximum average number of steps

intervaldata[intervaldata$Avg==maximumSteps,1]


## Imputing missing values

## Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

nrow(activity[is.na(activity$steps),])


## Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
## Use mean value for missing values

## Create the average number of steps per day / interval

avgdata <- ddply(nomiss, .(interval, day), summarize, Avg = mean(steps))

## Create dataset with only NAs 

missingdata<- activity[is.na(activity$steps),]

## Merge NA data with average weekday interval 

mergedata<-merge(missingdata, avgdata, by=c("interval", "day"))

## Create a new dataset with missing data now filled in.


mergedata2<- mergedata[,c(6,4,1,2,5)]
colnames(mergedata2)<- c("steps", "date", "interval", "day", "DateTime")

## Merge the missing averages and non-missing data 

FinalData <- rbind(nomiss, mergedata2)

## Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?


sumsteps2 <- aggregate(FinalData$steps ~ FinalData$date, FUN=sum, )
colnames(sumsteps2)<- c("Date", "Steps")

## Mean of Steps with imputed missing data 

as.integer(mean(sumsteps2$Steps))


## Median of Steps with imputed missing data 

as.integer(median(sumsteps2$Steps))


## Creating the histogram of total steps per day - compare dataset with imputed data to data from first part of assigment to show impact

hist(sumsteps2$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with Imputed Data", col="Black")
hist(sumsteps$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with Imputed data", col="Grey", add=T)
legend("topright", c("Imputed Data", "Non-NA Data"), fill=c("black", "grey") )



## Are there differences in activity patterns between weekdays and weekends?

## Create a new dichotomous variable to identify if the day is a weekday or a weekend 

## Create new category based on the days of the week

FinalData$DayType <- ifelse(FinalData$day %in% c("Saturday", "Sunday"), "Weekend", "Weekday")

## Make a panel plot containing a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

library(lattice) 

## Summarize data by interval and weekend / weekday category

intervaldata <- ddply(FinalData, .(interval, DayType), summarize, Avg = mean(steps))

## Plot data in a panel plot

xyplot(Avg~interval|DayType, data=intervaldata, type="l",  layout = c(1,2),
       main="Average Steps per Interval Based on Type of Day", 
       ylab="Average Number of Steps", xlab="Interval")
